version: "1.0"
stages:
  - prepare
  - build
  - test
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "codefreshdemo/example_python_redis"
    revision: "master"
    git: github
    stage: prepare
  build_app_image:
    title: "Building Docker Image"
    type: "build"
    image_name: "python-redis-app"
    tag: "latest"
    dockerfile: "Dockerfile"
    stage: build
  build_test_image:
    title: "Building Docker Test Image"
    type: "build"
    image_name: "python-redis-app-tests"
    tag: "latest"
    dockerfile: "Dockerfile.test"
    stage: test
  run_integration_tests:
    title: "Running integration tests"
    stage: test
    image: '${{build_test_image}}'
    commands:
      # Redis and app are certainly up at this point
      - sh ./test.sh
    services:
      composition:
        redis:
          image: redis:latest
          ports:
            - 6379 
        web:
          image: '${{build_app_image}}'
          ports:
            - 80             
      readiness:
        timeoutSeconds: 30
        periodSeconds: 15
        image: '${{build_test_image}}'
        commands:
          - "nslookup redis"   
          - "nslookup web"
          - "nc -z redis 6379"
          - "nc -z web 80"
